### ISSUE TITLE
Wrong image is downloaded on 50% of the days

### ISSUE THREAD

**Issue by rootofallevil144** [marguerite/linux-bing-wallpaper#26]
![screenshot](https://user-images.githubusercontent.com/40410320/41630136-ca2f7f32-742d-11e8-94e4-971eaa5ff3f9.png)

On ~50% of the days the actual image downloaded is not the picture of the day but a picture of a tropical island as seen on the screenshot.

The screenshot is done with the commit: c69f79f7456d27b9e3ee6a2175fddf5b11ad2112
The script is stared with the following command:
$ DESKTOP_SESSION=WM ./bing-wallpaper -market=en-US

**Comment by marguerite** [comment]
Which desktop environment? Do you have /usr/bin/feh installed?

**Comment by rootofallevil144** [comment]
I'm using openbox with archlinux.
Yes, "feh" is installed.

**Comment by marguerite** [comment]
the tropical island was a previous wallpaper...it means bing-wallpaper at least succeed once, can you paste the output of “journalctl  —user-unit bing-wallpaper”?

**Comment by marguerite** [comment]
Ha...I see...sorry for the inconvenience...

openbox is a WM.

bing-wallpaper needs to detect multiple DEs, when calling by systemd, it can not be sure it is started after the DE, so I can not let it fallback to “WM” by default blindly. So I invented this:

The first time it starts, it return DE as null, the loop for the next hour, if it is still null, then set to WM.

I am using plasma 5 with systemd, so I didn’t take care of the condition that user may start it without looping. 

So in your case, the DE always returns null so no download and set happened...

Can you tell me if there’s anything I can take advantage of to detect openbox?

**Comment by marguerite** [comment]
Is there any unique environment variable or process that openbox use to identify itself? Like XDG_CURRENT_DESKTOP or DESKTOP_SESSION?

**Comment by rootofallevil144** [comment]
I set environment variable "DESKTOP_SESSION" to "WM"
as I showed in the example:
$ DESKTOP_SESSION=WM ./bing-wallpaper -market=en-US
And the script downloads and sets the background image as it should.

**The problem is the image itself: half of the time it is not the actual Bing image of the day.
E.g. on June 18th 2018 the image was the right one ("Here, fishy!"). But today the image downloaded and set up by the script is the tropical island seen on the screenshot instead of the actual image (which is "Today is World Refugee Day" with black map and migration routes highlighted). The wrong image is always the same and remains wrong the whole day through, no matter how often I restart the script.**

P.S. I do not see any environment variables which indicates openbox. You can try to use "wmctrl -m" to detect it.

**Comment by marguerite** [comment]
What’s the “upstream uri:” in stdout then? And try visit it?

I will see the implementation of wmctl

**Comment by rootofallevil144** [comment]
```
upstream uri:http://bing.com/az/hprichbg/rb/WorldRefugeeDay_EN-US5421237644_1920x1200.jpg
```
But it opens as "https://www.bing.com/s/hpb/NorthMale_EN-US8782628354_1920x1200.jpg"

**Comment by marguerite** [comment]
err...

Can you please give me the whole output? The “upstream uri”, “downloaded to”, and “picture location”

**Comment by rootofallevil144** [comment]
started bing-wallpaper
upstream uri:http://bing.com/az/hprichbg/rb/WorldRefugeeDay_EN-US5421237644_1920x1200.jpg
setting wallpaper for wm
the picture location:/home/a1/Pictures/Bing/WorldRefugeeDay_EN-US5421237644_1920x1200.jpg

**Comment by marguerite** [comment]
And /home/a1/Pictures/Bing/WorldRefugeeDay_EN-US5421237644_1920x1200.jpg is the tropical island?

**Comment by rootofallevil144** [comment]
Yes

**Comment by rootofallevil144** [comment]
```
http://bing.com/az/hprichbg/rb/WorldRefugeeDay_EN-US5421237644_1920x1200.jpg
```
is the tropical island as well. Though the name suggest that it has to be the refugee day picture.

**Comment by marguerite** [comment]
BTW, can you please give me the output of “wmctl -m”?

**Comment by marguerite** [comment]
It was my fault.

If a resolution doesn't exist, bing will return a previous picture that has that resolution.

BTW the black world map is not a picture but a video. Do you know if it can be used as wallpapaer?

**Comment by rootofallevil144** [comment]
```
$ wmctl -m
Name: Openbox
Class: 
PID: N/A
Window manager's "showing the desktop" mode: OFF
```
> BTW the black world map is not a picture but a video. Do you know if it can be used as wallpaper?
Didn't know that. A proprietary app an my android phone made a picture out of it.

Today's picture loads correctly with the old version. I'll try the fix and will give you feedback after several days.

**Comment by marguerite** [comment]
@rootofallevil144 you can try latest version without DESKTOP_SESSION env, I learned something from wmctl...so now WMs supported by wmctl should be supported by bing-wallpaper too.

**Comment by rootofallevil144** [comment]
openbox is detected now automatically. I toggled through all the available markets and everything seems alright. Many thanks.

By the way could you please tell me if 1920x1200 the highest available resolution for bing images?

**Comment by marguerite** [comment]
@rootofaevil144

Yes. bing will not return 404 for a resolution if there’s any picture matches it. I modify my script to detect 404. All other resolutions returns 404.
