### ISSUE TITLE
Use --bg-fill instead of --bg-tile when using feh

### ISSUE THREAD

**Issue by ibot3** [marguerite/linux-bing-wallpaper#34]
When setting the background with feh, the `--bg-fill` option should be used instead of the `--bg-tile` option, as the tile option does not display the background correctly with multiple monitors and resolutions.

https://github.com/marguerite/linux-bing-wallpaper/blob/master/bing-wallpaper.go#L338

**Comment by marguerite** [comment]
Fixed
